# -*- coding: utf-8 -*-
"""NUMPY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYFO2QDZ57dar2GTpdAnSqtFXKeWQpGD
"""

import numpy as np
import pandas as pd
import requests

# Read Excel file
df = pd.read_csv('https://docs.google.com/spreadsheets/d/1dutcayQX1BjQsvw-tOE_8QJlLfhHOlLqcqudlcyW294/gviz/tq?tqx=out:csv')
df = pd.DataFrame(df)

df.head()

df.shape
df.dtypes
df = df.apply(pd.to_numeric, errors='coerce')

df.iloc[0, 0] = np.nan
df.iloc[:,0] = np.nan
df.iloc[:,1] = np.nan

df.columns
df = df.astype(float)
df.columns

Q1 = np.round(df.iloc[1:15,1:4].astype(float) * 7140.91, 2)
Q2 = np.round(df.iloc[1:15,4:7].astype(float) * 7145.50, 2)
Q3 = np.round(df.iloc[1:15,7:10].astype(float) * 7122.70, 2)
Q4 = np.round(df.iloc[1:15,10:13].astype(float) * 7322.7, 2)

df.iloc[1:15, 1:4] = Q1
df.iloc[1:15, 4:7] = Q2
df.iloc[1:15, 7:10] = Q3
df.iloc[1:15, 10:13] = Q4


df.to_excel("updated_data.xlsx", index=False)